# Generated by Django 3.1.5 on 2021-03-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('Value', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.BooleanField(default=True)),
                ('age', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('intime', models.DateTimeField(null=True)),
                ('outtime', models.DateTimeField(null=True)),
                ('room', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
